## GitHub Actions Workflow
# Last update: 2023-07-17


# Save this file to '.github/workflows/github-actions-workflow.yaml'


# Name of the workflow
name: GitHub Actions Workflow to run Python script on schedule


# Controls on when the workflow will run
on:

  workflow_dispatch:

  schedule:
    - cron: '00 10 * * *'
    - cron: '00 17 * * *'
    - cron: '30 21 * * *'
    - cron: '30 20 * * MON,THU'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Job name
  build:

    # Type of machine to run the job on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout repository content - https://github.com/actions/checkout
        uses: actions/checkout@v3


      - name: Install Google Chrome - https://github.com/browser-actions/setup-chrome
        uses: browser-actions/setup-chrome@v1


      - name: Setup Python - https://github.com/actions/checkout
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' #  Latest stable major version of Python


      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-dateutil geopy google-api-python-client google-auth lxml numpy pandas selenium webdriver-manager


      - name: Python - Get Python pathway
        run: which python


      - name: Run Python script
        if: |
          github.event.schedule == '00 10 * * *'
          || github.event.schedule == '00 17 * * *'
          || github.event.schedule == '30 21 * * *'
        run: python strava-club-scraper.py


      # - name: Run Python script
      #   if: |
      #     github.event.schedule == '30 20 * * MON,THU'
      #   run: python strava-club-scraper-activities.py
